name = "Matroids"
uuid = "15f40b7d-0f0d-4bdc-ab23-18b4f9c2ce47"
authors = ["aaaeide <andreasaaeide@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Allocations = "260a3f16-0ffa-4f23-875b-1350d3996fb5"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tectonic = "9ac5f52a-99c6-489f-af81-462ef484790f"
TikzGraphs = "b4f28e30-c73f-5eaf-a395-8a9db949a742"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
